### PR TITLE
release infotheo 0.7.3

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by affeldt-aist** [comment]
I do not understand the failure. It compiles fine on my machine with OCaml 5.0.

**Comment by affeldt-aist** [comment]
Ah but the last step is a compilation that might take several GB of RAM. Maybe there is a limitation in the CI?

**Comment by affeldt-aist** [comment]
@t6s has optimized a bit in memory usage the proof where failure occurs, should we try to re-release 0.7.3 (and substitute the tar.gz)?

**Comment by palmskog** [comment]
Code 173 is apparently OOM kill, so indeed runners ran out of memory. So we can merge.

**Comment by palmskog** [comment]
@affeldt-aist the preferred way to handle this is just to release a new minor version.

**Pull request merged**
