### PR TITLE
coq-simple-io.dev : remove dune upper bound

### PR DESCRIPTION
**Pull request by liyishuai**
as the Coq docker images have pinned Dune to 3.14.

### CODE REVIEW

**Comment by Lysxia** [comment]
The upper bound was to work around a bug (discussed [here](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/.5BERROR.5D.20The.20comp**.20of.20coq-core.2Edev.20failed.20at.20.22dune.20subst.22.2E)) that manifests itself on opam CI with dune 3.14. So if this PR doesn't pass CI, a more local workaround may be to allow newer dunes only in downstream configs such as QuickChick CI.

**Comment by liyishuai** [comment]
@erikmd is it worth downgrading the Dune version for coqorg/coq? Currently dev packages either fail the CI here or cannot be installed on the Docker images.
https://github.com/coq-community/docker-base/commit/c6bff6458708bc113b03c36619718720454eafc2

**Comment by erikmd** [comment]
Hi @liyishuai !
Sure, this is easy to do. Which version of Dune would be OK?

**Comment by erikmd** [comment]
Maybe 3.13.1 ?

unless the latest release 3.15.1 would fix the issue you speak about?

https://github.com/ocaml/dune/releases

**Comment by erikmd** [comment]
Hi @liyishuai, the downgrade is complete, see e.g.:
* https://explore.ggcr.dev/?image=coqorg/coq:dev
* [https://explore.ggcr.dev/?blob=coqorg/coq@sha256:…&mt=application%2Fvnd.docker.container.image.v1%2Bjson&size=11512&manifest=coqorg/coq:dev@sha256:…](https://explore.ggcr.dev/?blob=coqorg/coq@sha256:efc39f70af390282861ab1a38f94d4faf92b803982b3191dec74af8a15a9a645&mt=application%2Fvnd.docker.container.image.v1%2Bjson&size=11512&manifest=coqorg/coq:dev@sha256:0f92df0e921c1981287cf35f299c29913b6fe7b5956a4613d653ffd4d625a1ea)

Do you think you could file an issue in Dune's repo if it is not already the case?

Also Cc @ybertot FYI

**Comment by liyishuai** [comment]
Now there's https://github.com/ocaml/dune/releases/tag/3.15.2. Maybe worth testing it on Coq CI.

**Comment by liyishuai** [comment]
Seems ready to merge.

**Pull request merged**
