### PR TITLE
CertiCoq dev with Coq 8.19

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Seems broken
~~~
# coqc -R ./ CertiCoq.Benchmarks -R lib CertiCoq.Benchmarks.lib tests.v
# File "./tests.v", line 8, characters 0-45:
# Error: Cannot find a physical path bound to logical path
# CertiCoq with prefix CertiCoq.Plugin.
~~~

**Comment by liyishuai** [comment]
I was copying the OPAM file in the master branch: https://github.com/CertiCoq/certicoq/blob/master/coq-certicoq.opam

@mattam82 Which OCaml version should we run CertiCoq with?

**Comment by mattam82** [comment]
We use a docker image on our CI:
```

**Comment by mattam82** [comment]
with-test targets won't work. They assume an already installed CertiCoq iirc.

**Pull request merged**
