### PR TITLE
Make coq-interval.4.8.0 compatible with flocq 4.1.2

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by silene** [comment]
This patch is not sufficient to make CoqInterval compatible with Coq 8.18, so it is kind of pointless, since CoqInterval is already compatible with 8.17.

**Comment by JasonGross** [comment]
While the commit description claims that it is about compatibility with https://github.com/coq/coq/pull/16920, I believe in fact the patch is about compatibility with https://gitlab.inria.fr/flocq/flocq/-/merge_requests/22 (which itself was for compatibility with https://github.com/coq/coq/pull/16920).  Otherwise I believe coq-interval will fail to build with Coq 8.17 and flocq 4.1.2

**Comment by silene** [comment]
If the issue is caused by Flocq 4.1.2, I prefer to fix the issue on Flocq's side rather than to patch all the developments that rely on Flocq.

**Comment by JasonGross** [comment]
That would also work.  If you do as [I suggested on Zulip](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/building.20coq-interval/near/379362922) and make the top level compat definitions `#[local]` in Flocq, I think that should fix the issue.  (It's possible interval will still need this code for compat with Coq 8.18---i haven't checked---but I'm guessing not.)

**Comment by silene** [comment]
I am doubtful of the portability of `#[local]`, but `Module Import` should do the trick. So, closing in favor of #2711.

**Comment by JasonGross** [comment]
Thanks for the quick release of a fixed flocq!  I guess `#[local]` may be pretty recent, but https://github.com/coq/coq/commit/d1321c8d686cc0e392c8ae26beb8abe762258900 shows that `Local Definition` dates back to 8.5beta1 at least.  But indeed `Module Import` also works fine.

**Pull request closed without merging**
