### PR TITLE
QuickChick v1.0.0 for Coq 8.7

### PR DESCRIPTION
**Pull request by lemonidas**

### CODE REVIEW

**Comment by gares** [comment]
it is actually 4.05, still not >= 4.06

**Comment by gares** [comment]
You are misunderstanding my remark.

The current (and next) version of Coq is supposed to work with 4.02.
With this dependency  (>= 4.05) users with a perfectly valid installation of Coq will not be able to install your package.

Is this what you want?

**Comment by gares** [comment]
> it is actually 4.05

it is 4.05 on CI, maybe I was not clear

**Comment by lemonidas** [comment]
Actually, I just tried compiling and testing QuickChick locally in all switches after 4.02.3.
It seems that this release supports >= 4.04.0, because the mutation testing tool relies on standard library functions (e.g. in Filename) introduced in 4.04.0. I'm updating the pull request to reflect that. 

I'll try to make the next release as backwards compatible as possible by removing such uses, but for now 4.04.0 seems like a necessary requirement.

**Pull request merged**
