### PR TITLE
Update multinomials 2.3.0

### PR DESCRIPTION
**Pull request by CohenCyril**

### CODE REVIEW

**Comment by CohenCyril** [comment]
waiting on mathcomp 2.3.0 I guess?

**Comment by palmskog** [comment]
@CohenCyril I don't understand why this was marked as a draft. The only failure in CI was an opam timeout on the "any" job which is unrelated to the package, all other jobs passed.

**Comment by CohenCyril** [comment]
Ok! I was just lacking the time to investigate

**Comment by palmskog** [comment]
Wait, even though CI passed, I don't understand how this build can install anything meaningful when there is no `dune-project` or `dune` file in the archive (and Dune is not the build system used in CI). I'll investigate.

**Comment by CohenCyril** [comment]
Ah damnit... The build system was reverted to gnu make :facepalm:

**Pull request merged**
