### PR TITLE
Allow dune >= 3.15.3 in all packages restricting dune to < 3.14

### PR DESCRIPTION
**Pull request by MSoegtropIMC**

### CODE REVIEW

**Comment by silene** [comment]
Unfortunately, Dune >= 3.14 (which includes 3.15.3) is incompatible with the way our continuous integration is setup, as you can see from the failures. (My hypothesis is that `dune subst` does not support the fact that the home directory contains an `opam` component.)

Polluting the `opam` files of `coq-core` with the upper bound on `dune` is certainly crude, but it gets the continuous integration running. It would be better to somehow enforce the upper bound in `scripts/opam-coq-setup-root`, for instance. But nobody investigated how to do that properly.

**Comment by SkySkimmer** [comment]
Doesn't seem to work

**Comment by MSoegtropIMC** [comment]
The issue is that there are some coq opam packages which do require dune >= 3.14. Also in Coq Platform I had to upgrade to dune 3.15.3 cause of issues.

IMHO it should be discussed with the dune team if the way the CI is setup will permanently be incompatible with dune - in this case the only way is to change the CI setup - or if dune will be made compatible in the near future.

**Comment by SkySkimmer** [comment]
cc @rgrinberg

**Comment by erikmd** [comment]
just FYI @rgrinberg, the issue at stake is: https://github.com/ocaml/dune/pull/9895#issuecomment-2090414009

**Comment by rgrinberg** [comment]
Not sure I really understand the issue, but you might be able to fix if you disable substitution altogether with (subst disabled) in the dune-project file. To help out more, I will need a ticket with a more complete description of the problem.

**Comment by MSoegtropIMC** [comment]
Closed in favour of https://github.com/coq/opam/pull/3228 - this follows the approach also used in the Coq released packages.

**Pull request closed without merging**
