### PR TITLE
Add dependency to coq-elpi in coq-corn.dev

### PR DESCRIPTION
**Pull request by MSoegtropIMC**

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
Since this is "dev" which has been called "pretty much wild west" before I will self merge as soon as CI passes unless someone protests until then.

**Comment by SkySkimmer** [comment]
Looks like elpi is failing
~~~
- File "theories/dune", line 5, characters 11-20:
- 5 |  (theories elpi_elpi))
-                ^^^^^^^^^
- Theory "elpi_elpi" has not been found.
- -> required by theory elpi in theories/dune:2
- -> required by theory elpi_examples in examples/dune:3
- -> required by _build/default/examples/example_abs_evars.vo
- -> required by
-    _build/install/default/lib/coq/user-contrib/elpi_examples/example_abs_evars.vo
- -> required by _build/default/coq-elpi.install
- -> required by alias install
~~~
cc @gares

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : what I don't quite understand: elpi is on coq-ci - does fail there on its own as well?

**Comment by SkySkimmer** [comment]
I guess it's missing https://github.com/LPCIC/coq-elpi/commit/069018b9009f9bc5179cb08d714d681a114d6e14 here

**Comment by MSoegtropIMC** [comment]
> I guess it's missing [LPCIC/coq-elpi@069018b](https://github.com/LPCIC/coq-elpi/commit/069018b9009f9bc5179cb08d714d681a114d6e14) here

This has been merged 2 days ago. How can it fail today lacking this?

**Comment by SkySkimmer** [comment]
because it's a opam file change so it needs to be copied to this repo

**Comment by gares** [comment]
Right, but I cannot do it today

**Comment by MSoegtropIMC** [comment]
> because it's a opam file change so it needs to be copied to this repo ("here")

Ah yes, sorry.

Shall I piggy pack it to this PR?

**Comment by gares** [comment]
Yes please

**Comment by MSoegtropIMC** [comment]
Done.

**Comment by MSoegtropIMC** [comment]
I now get while building `coq-elpi.dev`:
```
# +  File "./test.v", line 1, characters 0-39:
# +  Error: Cannot load Stdlib.Strings.String: no physical path bound to
# +  Stdlib.Strings
```
@gares ?

**Comment by gares** [comment]
Looks like the dune files foe the tests miss the stdlib dep. I Don't get why I did not figure it out upstream

**Comment by MSoegtropIMC** [comment]
Thanks! Please ping me as soon as the up stream fix is done.

**Comment by gares** [comment]
should work now

**Comment by MSoegtropIMC** [comment]
Thanks. I will rebase the PR to trigger a new CI.

**Comment by MSoegtropIMC** [comment]
@gares : So I guess the "stdlib-shims" need to remain and I should just remove the second commit from this PR?

**Comment by MSoegtropIMC** [comment]
As announced last Monday I self merge as soon as CI passes => merge.

**Pull request merged**
