### PR TITLE
GeoCoq.2.4.1

### PR DESCRIPTION
**Pull request by Boutry**

### CODE REVIEW

**Comment by palmskog** [comment]
@Boutry we get the following error in CI:
```
#=== ERROR while compiling coq-geocoq-axioms.2.4.1 ============================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.11.2 | file:///builds/coq/opam/released
# path                 ~/opam-root-4.11.2-2.1.2-sandbox/4.11.2/.opam-switch/build/coq-geocoq-axioms.2.4.1
# command              ~/opam-root-4.11.2-2.1.2-sandbox/opam-init/hooks/sandbox.sh build make -j2
# exit-code            2
# env-file             ~/opam-root-4.11.2-2.1.2-sandbox/log/coq-geocoq-axioms-127364-c676f6.env
# output-file          ~/opam-root-4.11.2-2.1.2-sandbox/log/coq-geocoq-axioms-127364-c676f6.out
### output ###
# COQDEP VFILES
# make[1]: *** No rule to make target 'Utils/general_tactics.vo', needed by 'Axioms/tarski_axioms.vo'.  Stop.
# make: *** [Makefile:327: all] Error 2
```
Maybe some dependency is missing for `coq-geocoq-axioms`?

**Comment by Boutry** [comment]
Hi @palmskog,

I saw that. It seems to be the same error for the 4.07.1, 4.11.2 and the "any" test. However, it worked with 4.14.0 and 5.0.0. I checked and Utils/general_tactics.vo is produced during the compilation of coq-geocoq-coinc.2.4.1. So, is it some error linked to the _CoqProject which is not properly setup for the vo to be found afterwards? I managed to get a configuration on my laptop able to reproduce the error so I should be able to test whether a fix solves the issue before pushing. But I was not sure how to fix it. Do you have a suggestion?

On another topic, I tested the compatibility with the versions of Coq and math comp manually. I managed to compile GeoCoq, release 2.4.1, with Coq 8.7-8.11.2 and mathcomp 1.6.4-1.10.0, letting spam choosing the version of ocaml to avoid adding another "space" multiplying the number of dependencies to check manually. I did not see something that hinted that your CI checks these compatibility. If the CI succeeds, will we be sure that these versions will be compatible?

**Comment by palmskog** [comment]
@Boutry the tests for 4.14.0 and 5.0.0 "passed" because those OCaml versions don't support the Coq version used by these packages:
> Skipping coq-geocoq.2.4.1 since not installable with the current compiler

As for fixing this error, I can't give much general advice, since your build process uses quite a few custom build commands. Our standard approach is to rely only on builds directly via `coq_makefile` or Dune, e.g.,
```
build: [make]
```
and handle all custom configuration via `coq_makefile` in the project itself.

We don't really check all versions of Coq+MathComp, only that it works with the "upper bound" of the opam specification (Coq 8.11.2 and MathComp 1.10.0 in your case). Testing all combinations of Coq and MathComp allowed by a package would probably make most CI runs take several hours, and generally our interest is mostly with the latest supported version of everything.

**Comment by Boutry** [comment]
Our scripts only list the files that belong in a given package and add the to the _CoqProject before using coq_makefile.

https://github.com/GeoCoq/GeoCoq/blob/master/configure-coinc.sh

I remember that we added some extra folders with Enrico when we packaged the previous release.

https://github.com/coq/opam/blob/master/released/packages/coq-geocoq-pof/coq-geocoq-pof.2.4.0/opam

Is is something worth testing? There might be some files that belong to the Utils folder in both coq-geocoq-coinc and coq-geocoq-axioms for example. I guess I can try to mimic this and create a Utils2 where I put the files compiles by coq-geocoq-axioms.

Ok so my test will have to do :) Is there a possibility that, while the compilation worked on my laptop, it might not work on someone else's?

Also, for the next release that I hope to do this week, is it worth splitting into that many packages? I believe we did this since GeoCoq used to take a relatively long time to compile but my latest commit compiles in less than 3 minutes on my laptop. It is pretty recent and I should check the time it takes on an older one. I have one from 2019 which might give a more average compilation time. So is there some sort of guideline on the time a package should be compiled in?

**Comment by palmskog** [comment]
@Boutry based on my experience, these kinds of Coq compilation issues need careful debugging of scripts and commands. It's a good idea to recreate the same error without using opam. The error message seems to indicate that this has to do with missing dependencies: the file `Utils/general_tactics.vo` can't be assumed to exist when installing the `axioms` package. If this file lives in some other package, it should be added as a dependency of the `axioms` package. Failing that, source files inside the archive may need patching.

There are essentially two reasons to break a project down into multiple packages:
- easier reuse, people depend on exactly what they need
- compilation time

If you believe compilation time is no longer an issue, this could be an argument in favor of making it a single package. But on the other hand, using a build system like [Dune](https://dune.build) makes it easy to manage several interdependent packages, see for example the `.opam` files here: https://github.com/coq-community/hydra-battles

**Comment by silene** [comment]
`GeoCoq.Utils.general_tactics` is shipped by the `coq-geocoq-coinc` package (which is fine), and the `coq-geocoq-axioms` package depends on it (which is fine). But when it comes to compiling `Axioms/tarski_axioms.v`, `CoqMakefile` becomes confused. Indeed, `Axioms/tarski_axioms.v` depends on `GeoCoq.Utils.general_tactics`, but there is a file `Utils/general_tactics.v` in the currently built project. So, `CoqMakefile` has no way to understand that `GeoCoq.Utils.general_tactics` is supposed to come from the external world (and thus does not need to be compiled), since it is present in the local path (because of `-R . GeoCoq`).

**Comment by silene** [comment]
And to be clear, I am saying that `coq_makefile` is confused, but it is actually `coqdep` which is confused. (And this is not a bug or a limitation of `coqdep`. The tool just does not have enough information to know that the local file is not meant to be a build dependency.)

**Comment by Boutry** [comment]
I will look how much time, the current version takes to compile. Maybe it is just easier to do just one package since I am not sure that the "easier reuse, people depend on exactly what they need" applies. What would be an acceptable time for the compilation?

**Comment by palmskog** [comment]
A very subjective build time scale based on my observations:
- less than a minute is ideal
- a few minutes is usually fine
- 5-10 minutes is bearable
- 10-20 minutes is annoying
- 20+ minutes requires you to really want to install the project

All of this can be assumed to be on a reasonably modern laptop, with 4+ physical cores. If people have less, they will be more tolerant to longer compilation due to outdated hardware.

**Comment by Boutry** [comment]
I just did a test and it takes 5m30 on my M2 MacBook Air which has 24 GB or RAM. I think GeoCoq can be split into two parts: the main part linked to the formalization of Tarski's book and some extra results, and another part about Euclid's Elements which is mostly independent. I think Julien wanted the part that relies of mathcomp to be independent. Since, even for v2.4.1, it consists of a single files (it would be more for v2.5.0), it allowed to have most of the results without having an added dependency. The first packages were too atomic for my taste and it is precisely where the issue is. So I will try this splitting which may solve the issue. If it works I can just add the needed scripts as extra files to the packages.

I will try and add a build system like Dune for v2.5.0.

**Comment by Boutry** [comment]
Doing `opam repo add test ./released` inside `opam-coq-archive` and then `opam install -v coq-geocoq.2.4.1` worked. Let's see if the CI agrees.

**Pull request merged**
