### PR TITLE
[Tactician] Upgrade minimum dune after fix of ocaml/dune#8958

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**

### CODE REVIEW

**Comment by silene** [comment]
Note that, despite the "success" status of the CI, it never succeeded in installing any of the packages. (I suppose that we should at least tweak the `build:any` job, so that it becomes an error if it installed nothing, rather than a vacuous success.)

**Comment by LasseBlaauwbroek** [comment]
Indeed. I don't really understand what is going on anyway. The logs say that the package cannot be installed with the current compiler. But then, the subsequent message says that the package can be installed without changing to another compiler....

**Comment by silene** [comment]
This is just a wild guess, but I think you are confusing `opam` by having a dependency on `opam-client`. As a consequence, it would have to reinstall itself on the fly to succeed, which I guess it really does not want to do.

**Comment by LasseBlaauwbroek** [comment]
I had forgotten to update some requirements, leading to no solution existing. The tests pass now (non-vacuously).

**Pull request merged**
