### PR TITLE
[released] Make it possible to build `mathcomp/mathcomp:2.2.0-coq-dev`

### PR DESCRIPTION
**Pull request by erikmd**
href: https://github.com/math-comp/docker-mathcomp/pull/32#issuecomment-1896075150

Cc @proux01 @pi8027 FYI

### CODE REVIEW

**Comment by pi8027** [comment]
Thanks!

**Comment by proux01** [comment]
BTW @erikmd could you also PR that change to mathcomp itself? so that we avoid doing the mistake again and again at next releases (the .opam files come from the math-comp repo).

**Comment by erikmd** [comment]
Hi @proux01 

I don't think there's something to change in:
https://github.com/math-comp/math-comp/blob/7b1705949f6f2554cc9ffca562ecd97796c6cf84/coq-mathcomp-ssreflect.opam#L12-L18

```
depends: [
  ( ( "coq" {>= "8.16" & < "8.17~"} & "elpi" {>= "1.16.5"} ) |
  # The line above can be removed at the time support for 8.16 is dropped
    ( "coq" {>= "8.17"}
    & "elpi" {>= "1.17.0"} ) )
  "coq-hierarchy-builder" { >= "1.5.0"}
]
```

Because `{>= "8.17"}` already includes the version `"dev"`, lexicographically speaking.

Anyway, adding a mere comment could help, maybe → feel free to add one such comment in coq-mathcomp-ssreflect.opam or in the math-comp wiki ^^

**Comment by proux01** [comment]
Sure but when releasing, the persons doing the release are likely to want to add an upper bound and forgot about dev (at least that's what happened yesterday, and similar things already happened during previous releases). So maybe having the two things in sync would be more error proof.

**Comment by proux01** [comment]
Hre it is https://github.com/math-comp/math-comp/pull/1161

**Pull request merged**
