### PR TITLE
add 8.19.dev core-dev packages

### PR DESCRIPTION
**Pull request by palmskog**
ci-skip: coq-core.8.19.dev coq-stdlib.8.19.dev coqide-server.8.19.dev

### CODE REVIEW

**Comment by palmskog** [comment]
@SkySkimmer do all 8.19 packages really depend on `odoc`, or is this just Dune-generated boilerplate?

**Comment by palmskog** [comment]
But the 8.18 packages also had `build @doc`, but no dependency on `odoc`. So I guess the question for @ejgallego is if something changed under the hood for 8.19 w.r.t. Dune+documentation.

**Comment by ejgallego** [comment]
I guess that was a bug in the 8.18 packages?

The doc target requires `odoc`.

**Comment by palmskog** [comment]
@ejgallego @SkySkimmer the `coq` package's `build @test` did not work properly without adding `ounit2` as a dependency. Is this something I should report or fix upstream?

**Comment by SkySkimmer** [comment]
The ounit dep should be on coq not coq-core yes

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/18389

**Pull request merged**
