### PR TITLE
release infotheo 0.6.1

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by affeldt-aist** [comment]
Oops, the log seems to indicate a compilation error with MathComp-Analysis 0.7.0.

**Comment by affeldt-aist** [comment]
That maybe related to that MathComp-Analysis issue though the log looks different: https://github.com/math-comp/analysis/issues/1169

**Comment by affeldt-aist** [comment]
Note also that we tested a few combinations of recent versions of mathcomp and coq before submitting (see https://github.com/affeldt-aist/infotheo/commit/15762a0fc4c65f3de68b12ec3ee877b97b98fb2e)

**Comment by palmskog** [comment]
I don't know exactly what is going on here, but it looks like an OOM kill, so let's merge.

**Pull request merged**
