### PR TITLE
release monae 0.7.1

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by palmskog** [comment]
@affeldt-aist there is not a single successful build here due to OOM kills. Can you point to some example of a successful build somewhere?

**Comment by affeldt-aist** [comment]
The last commit here https://github.com/affeldt-aist/monae is such an example.

**Comment by affeldt-aist** [comment]
But it is true that there is a file (that has not changed recently, `smallstep.v`) that now requires a ridiculous amount of memory and time to compile (very slow `Qed`).

**Comment by palmskog** [comment]
I suspected as much (about the single file using lots of memory). But as usual, then please consider making a new release to address this.

**Comment by affeldt-aist** [comment]
Sure, we will, we really just didn't notice.

**Pull request merged**
