### PR TITLE
release infotheo 0.7.6

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by palmskog** [comment]
@affeldt-aist this [run](https://github.com/coq/opam/pull/3264/checks?check_run_id=34652962637) looks like a genuine error, could you take a look?
```
# [HB.non-forgetful-inheritance,HB,elpi,default]
# File "./probability/convex.v", line 1972, characters 0-151:
# Error:
# HB: archimedean.Num.NumDomain_isArchimedean.axioms_ is not a factory or its library (mathcomp.algebra.archimedean.Num) was not correctly imported
```

**Comment by affeldt-aist** [comment]
As I feared, the problem occurs with Hierarchy-Builder 1.8.0 only. @gares @CohenCyril

**Comment by affeldt-aist** [comment]
Ah but the fix is easy and correctly hinted at by the error message!

**Comment by affeldt-aist** [comment]
It looks like I am good for another minor release...

**Pull request merged**
