### PR TITLE
MetaCoq 1.3 for Coq 8.17

### PR DESCRIPTION
**Pull request by mattam82**
ci-skip: coq-metacoq-common.1.3+8.17 coq-metacoq-erasure-plugin.1.3+8.17 coq-metacoq-erasure.1.3+8.17 coq-metacoq-pcuic.1.3+8.17 coq-metacoq-quotation.1.3+8.17 coq-metacoq-safechecker-plugin.1.3+8.17 coq-metacoq-safechecker.1.3+8.17 coq-metacoq-template-pcuic.1.3+8.17 coq-metacoq-template.1.3+8.17 coq-metacoq-translations.1.3+8.17 coq-metacoq-utils.1.3+8.17

See https://github.com/MetaCoq/metacoq/releases/tag/v1.3-8.17

### CODE REVIEW

**Comment by mattam82** [comment]
We are hitting again the limits of the CI machines, while the package compiles fine in other CIs (e.g. https://github.com/yforster/coq-malfunction/actions/runs/8188486170/job/22391129882), but also many other CIs we run in dependent projects...

**Comment by mattam82** [comment]
I don't see how to fix the branch target to fetch the ci-skip information easily. If you look at the exported variables, nothing refers to 2979 anymore, and we don't get the mattam82 repo either. So we have to pass some information from elsewhere. @gares ?

**Comment by mattam82** [comment]
> The branch is supposed to be called `pr-2979` on the CI repository and that is how the script recovers the PR number. What change has caused the created branches to no longer follow this naming?

It is this name in the `(pull request)` job but not in the `(branch)` job indeed.

**Comment by mattam82** [comment]
Maybe one of the coqbot maintainers has an idea (@JasonGross @Zimmi48)

**Comment by JasonGross** [comment]
Maybe the CI should be disabled for branches other than master?  No need to run it on both branch and PR, right?

**Comment by silene** [comment]
I don't see the relevance. This is a standard PR against `master`. Or do you mean that, because CI is also enabled for PR against other branches, this messes the way branches are named?

**Comment by silene** [comment]
I am extremely confused. The `export` change does not make sense, but the `s/opam-coq-archive/opam/` does. Except that it does not:
```
$ git remote -v
origin	git@github.com:coq/opam-coq-archive.git (fetch)
origin	git@github.com:coq/opam-coq-archive.git (push)
```

What the f is happening here? Did someone stealthily rename the project? How come everything keeps working?

**Comment by palmskog** [comment]
Maxime renamed the repository from `opam-coq-archive` to `opam`, and GitHub always introduces a redirect from an old repository name to the new one.

**Comment by mattam82** [comment]
They should be, CI_BUILD_REF_NAME was deprecated for CI_COMMIT_REF_NAME a while ago (see e.g. https://github.com/example42/psick/issues/273) and the repo was renamed to `opam` I don't know when, so the old curl command was giving a useless permanently moved response. Fixing this is the only way I found for ci-skip to work at least for the pull_request pipelines.

**Comment by mattam82** [comment]
Oh I see what you mean about export, I used it just to help debugging (seeing what variables were defined). I should have added a `;` though.

**Comment by mattam82** [comment]
I removed the commit adding the `export`

**Comment by mattam82** [comment]
Again, we have a failing job due to runners limits (OOM I think).

**Comment by mattam82** [comment]
Thanks @silene !

**Pull request merged**
