### PR TITLE
Release of SMTCoq 2.2

### PR DESCRIPTION
**Pull request by ckeller**
This PR:
- adds opam files for SMTCoq-2.2, for Coq 8.13 to 8.19
- updates opam files for the development version.

### CODE REVIEW

**Comment by ckeller** [comment]
Hi
I do not understand the error...?

**Comment by silene** [comment]
```
# CAMLOPT -c -for-pack Smtcoq_plugin ../3rdparty/alt-ergo/smtlib2_lex.ml
# File "../3rdparty/alt-ergo/smtlib2_lex.ml", line 1:
# Error (warning 70 [missing-mli]): Cannot find interface file.
# make[2]: *** [Makefile:668: ../3rdparty/alt-ergo/smtlib2_lex.cmx] Error 2
```

Apparently, your archive does not contain a file `3rdparty/alt-ergo/smtlib2_lex.mli`, so OCaml complains that it is missing.

**Comment by ckeller** [comment]
Thanks @silene , I did not find this error message.
The .ml file is generated by Ocamllex, which does not generate .mli. So having this warning as blocking is a problem in that case...

**Comment by ckeller** [comment]
Actually I already had the problem https://github.com/coq/opam/pull/2609 . In this PR, I skipped the 8.13 version, but now I have a new release also for this version.

**Comment by silene** [comment]
Since only coq-smtcoq.dev+8.13 failed, I am merging. But you might still want to remove this development package.

**Comment by ckeller** [comment]
Thanks! Why is there this blocking warning specifically for 8.13?

**Comment by silene** [comment]
This OCaml warning did not exist at the time, so Coq 8.13 did nothing special about it. Later versions of Coq, however, were aware of it and disabled it. (In other words, the issue occurs if you use an OCaml compiler more recent than the one available at the time of Coq 8.13.) That said, there might exist some Makefile variable that you can add at the end of the command `make "-j%{jobs}%"` to work around the issue.

**Pull request merged**
