### PR TITLE
configuration fix for coq-vst.3.0beta2

### PR DESCRIPTION
**Pull request by andrew-appel**
Oops.  In #3013 we had a configuration issue that didn't show up in the CI, because the CI for VST uses an internal CompCert but the installed one uses the platform CompCert.  This fixes that; please merge this P.R.

### CODE REVIEW

**Comment by palmskog** [comment]
@andrew-appel @mansky1 now we unfortunately have a build error in CI:
```
# File "./veric/external_state.v", line 2, characters 0-47:
# Error: Cannot find a physical path bound to logical path
# excl_auth with prefix iris_ora.algebra.
```
any ideas?

**Comment by mansky1** [comment]
Yes, I forgot some post-processing on the archive I uploaded. Sorry, I'll have it fixed in a minute...

**Comment by mansky1** [comment]
That took longer than I expected, but I think it's working now! (Sorry for all the thrashing; this is my first time releasing an opam package, and I'm figuring out what needs to be tested as I go.)

**Comment by mansky1** [comment]
@palmskog I believe we're ready to merge.

**Pull request merged**
